### ISSUE TITLE
Screenshots are not shown in the report

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/zafira#1100]
It seems like after rerun failures screenshots are broken.

<img width="1348" alt="screenshot_console" src="https://user-images.githubusercontent.com/16190512/46810687-e2867680-cd79-11e8-936d-51d3a3f8454a.png">

**Comment by Boniara** [comment]
This error connected with temporary credentials expiration.
A presigned URL is only valid as long as the session key that was used when generating it. If we are authenticating as an IAM user with long-lived access keys, this is not a problem. But IAM roles use temporary access keys that cycle every 36 hours max.
Our session key has expired because we are getting the "The provided token has expired." error, which (as noted above) is a different error message than "Request has expired " which you get when the presigned URL reached its expiration date.
Our token has 12 hour limit.

**Comment by Boniara** [comment]
will be fixed after https://github.com/qaprosoft/zafira/pull/1133 will be merged
