### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by vlinsw** [qaprosoft/zafira#1675]
Hi, I followed the installation steps in the readme file. After running docker-composition, I did not make any changes. I tried qpsdemo/qpsdemo successfully logged in locally, and it always threw "invalid credentials" when logging on the remote machine.
Please help

**Comment by hursevich** [comment]
Take a look at: http://qaprosoft.github.io/zafira/getting_started/

If you are planning to access Zafira remotely you will need to modify docker-compose.yml specifying the appropriate IP address of your host:

environment:
  - ZAFIRA_URL=http://localhost:8080

So in this case you have to replace ZAFIRA_URL with you public host name or IP (instead of localhost).

**Comment by AbhiAuto** [comment]
We have tried changing the same and took tag version of framework 4.0.54. Still its showing invalid credentials. please let us know if we need to do any other configuration for database or softwares

**Comment by AbhiAuto** [comment]
Its working fine now. We did the changes as you have mentioned above.

@hursevich can I have your contact details?

**Comment by hursevich** [comment]
@AbhiAuto please join Telegram channel https://t.me/qps_zafira of use my personal email from the profile.

**Comment by vlinsw** [comment]
Thank you very much. Your solution solved my problem.
