### ISSUE TITLE
User is not able to mark as failed/passed test from mobile

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1908]
**Steps to reproduce**
1. Login to Zafira (Admin/User) from Mobile
2. Open test run tab
3. Open test run
4. Click on details (eye) on  passed test
5. Go out details window
6. Click on 3 dots on test
7.  Select Mark as failed

**Actual behavior**
User is not able to mark as failed test from mobile

**Expected behavior**
User is able to mark as failed test from mobile

**Environment**
ui v.1.27.RC1 | server v.4.1.81.RC1 | client v.4.1.65
safari
IOS 13.1.3

**Comment by danymill** [comment]
This is an iOS Safari bug rather than a Zafira bug, but it does affect Zafira since it uses the History API.

`alert/confirm/prompt` dialogs will not be displayed if the user has navigated back to a pushState location. Once a user has navigated back (at any point), calling `alert(…)`, `confirm(…)`, or `prompt(…)` will not display dialog boxes. `confirm(…)` will always return false, and `prompt(…)` will return null.

This has been raised on [StackOverflow](https://stackoverflow.com/questions/38083702/why-are-alert-confirm-and-prompt-not-working-after-using-js-history-api), along with a good [demonstration of the problem](http://htmlpreview.github.io/?https://gist.githubusercontent.com/anonymous/6eab8028289c64a623efcba652eb7446/raw/be9ecb6c2d08497a146b947266c06a0409aaeb5b/test.html).

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.24-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT.
