### ISSUE TITLE
All test runs (in progress status) are displayed at the top of the page

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#1918]
**Description**
If we open test runs, we can see a lot of runs with different status (in progress, finish), these runs are displayed by started time.
I think it will be more comfortable if all test runs (in progress status) are displayed at the top of the page, I suggest to sort test runs for displaying by status and start time

Actual:
<img width="350" alt="status" src="https://user-images.githubusercontent.com/3008517/70234508-d9244e80-1771-11ea-9cc4-1fb523f33995.png">

**Comment by nsidorevich** [comment]
@VitaliLiavitski this is not something we consider for implementation in the nearest future. Mainly because it's arguably useful - once such sorting is applied once test run completes it will go down in the list or maybe even to another pages depending on number of runs in progress which can be confusing for user. The idea is to keep it simple and predictable.
