### ISSUE TITLE
clicking to existing bug leads to incorrect url

### ISSUE THREAD

**Issue by imikulich** [qaprosoft/zafira#432]
![image](https://user-images.githubusercontent.com/18451544/34058886-e96a4d5c-e1dc-11e7-8b70-c63e4abada56.png)
leads to https://ua.qaprosoft.com/browse/DROID-9174
correct url is: https://underarmour.atlassian.net/browse/DROID-9174
![image](https://user-images.githubusercontent.com/18451544/34058994-5afba632-e1dd-11e7-9b95-bfe9d3165b88.png)

**Comment by kdaroshka** [comment]
The issue is reproducible again on Zafira 3.0.33.
1. Open https://ua.qaprosoft.com/zafira/#!/tests/runs/10603
2. Find failed test with assigned QAT
3. Click on QAT to open it in Jira
Actual result: USer is taken to `Cannot get QAT` screen (see screenshot)
Expecteed result: User can open QAT in Jira

![ice_screenshot_20180302-192236](https://user-images.githubusercontent.com/24683436/36909835-30d50c04-1e50-11e8-9b30-3f54057cc592.png)
