### ISSUE TITLE
Please, remove white (Queued) tests from test run

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#825]
I have a test run which contains almost 200 tests (and this is not the end)

1) it would be more then enough to see ONLY number of  queued tests in header
2) i see just enormous amount of white test in test run AFTER IT IS FINISHED - why?

**Comment by tsvrko** [comment]
1. Display of QUEUED will be disabled if testrun is in progress.
2. Now all the changes which have been made over the tests (e.g. renaming, deleting, commenting) are reflected as queued tests in the next test run, so as well as all this actions affect performance statistics, feature works according to the design and stores historical information about modifications provided since the latest run. 
In future will be implemented ability for a user to delete queued tests from Zafira if they don't exist anymore.
